### PR TITLE
Allow for VID input

### LINKED ISSUE #72: Changes to "Add VID" screen
**Is your feature request related to a problem? Please describe.**
As requested by MOSIP for demo

**Describe the solution you'd like**
1. Input field should accept either 10 or 16 digits
2. Screen for "Add VID" should have text "Enter the MOSIP-provided UIN or VID of the ID you wish to retrieve"
3. Input field should have input watermark "UIN or VID"

### PR DESCRIPTION
**Pull request by pmigueld**
Partially resolves #72 

Needs backend changes to accept VID when downloading credential. VC will get stuck at loading status trying to download otherwise.

### CODE REVIEW

**Review by danicaerediano — COMMENTED** [review]
I get error `Invalid id::VID is revoked` on entering 111111 as OTP for the 16 digits code

**Comment by pmigueld** [comment]
> I get error `Invalid id::VID is revoked` on entering 111111 as OTP for the 16 digits code

This is expected since VID is temporary, right @uocnb?

**Comment by uocnb** [comment]
> > I get error `Invalid id::VID is revoked` on entering 111111 as OTP for the 16 digits code
> 
> This is expected since VID is temporary, right @uocnb?

@pmigueld this depends on type of generated VID. It is defined by `vidType` parameter in the VID generation API payload.
- Perpetual => permanently, no expires.
- Temporary => expires time set by MOSIP.

**Review by kneckinator — APPROVED** [review]
Let's merge this and adapt if/when the VID format changes on the MOSIP side.

**Pull request merged**
