### PR TITLE
Feature/151 commit UI ios issues

### PR DESCRIPTION
**Pull request by nicholemnl**
Fixes idpass/inji/issues/151

### CODE REVIEW

**Comment by kneckinator** [comment]
Just performed an early review and it is looking good.

**Comment by nicholemnl** [comment]
Resolves the new found issues in https://github.com/idpass/inji/issues/151

**Comment by kneckinator** [comment]
@nicholemnl @pmigueld Can we aim to merge this as soon as the 0.3.0 release is done, so that we can start to make regular tests on iOS?

FYI: @jeremi @kyanthony

**Review by danicaerediano — APPROVED** [review]
tested on android device and there were no issues encountered

**Review by danicaerediano — APPROVED** [review]

**Review by pmigueld — APPROVED** [review]
iOS version now builds. 👍

**Pull request merged**
