### PR TITLE
Dev workflow issues with flavors 

### LINKED ISSUE #38: Dev workflow issues with flavors
- [x] idpass/idpass-mosip-resident-app#94
- [x] Build is being duplicated (see this [gist](https://gist.github.com/pmigueld/350e690eb57420d32878f0345aca71e4#file-build_error-log-L114))
- [x] Build fails with some permission issue sometimes (see this [gist](https://gist.github.com/pmigueld/9af61708940c0e1a85d2c51cba24a084))

### PR DESCRIPTION
**Pull request by rjmangubat23**
Fixes #38

### CODE REVIEW

**Review by pmigueld — COMMENTED** [review]
Tested and works (no longer duplicates the build) but I did observe in my machine that it sometimes disconnects from the dev session so debugging gets interrupted. Hoping that it's just something weird going on with the Cygwin environment. I will test again in Linux and see if it's more stable.

**Comment by pmigueld** [comment]
Tested in Linux and it's consistently being detached from the debugger. I don't think we can use this yet.

**Comment by pmigueld** [comment]
> Tested in Linux and it's consistently being detached from the debugger. I don't think we can use this yet.

This may have been related to the issue here: https://github.com/idpass/inji/pull/70
Will test again when I reboot into Linux.

**Comment by jeremi** [comment]
This is not reliably working, so we will not merge it and re-open it in case we find the solution.

**Pull request closed without merging**
