### PR TITLE
Read app credits from THIRPARTY.md

### LINKED ISSUE #28: Read app credits from THIRPARTY.md
After implementing idpass/idpass-mosip-resident-app#83 we should read the contents of the credits page from `THIRDPARTY.md`.

The contents could either be injected in to the component compile time or be read directly from `THIRDPARTY.md` when the credits page is accessed.

### PR DESCRIPTION
**Pull request by danicaerediano**
Closes #28

### CODE REVIEW

**Comment by danicaerediano** [comment]
using solutions suggested here: https://github.com/facebook/react-native/issues/2481 for images

**Comment by pmigueld** [comment]
This change no longer loads the images for [Credits.md](https://github.com/idpass/inji/blob/enhancement-28-credits-page/Credits.md) in this repo properly. And I think we can add some basic styling to keep it consistent with the app (like the font and spacing between headers).

image

**Comment by danicaerediano** [comment]
@pmigueld that's not how you add an image in a .mf dile, but I agree with the styling, will work on it

**Comment by pmigueld** [comment]
> @pmigueld that's not how you add an image in a .mf dile, but I agree with the styling, will work on it

If the Markdown processors allows it you can use an `` tag and it's necessary if you want to specify the size for the image. Anyway it was the image path that I was talking about, the new one does not load properly when viewing the credits file here on GitHub. You can restore the original path in the `.md` file and change this line in `Credits.tsx:54`

```js
source={images[node.target.split('/').pop()]}
```

**Review by pmigueld — APPROVED** [review]

**Pull request merged**
